"""
Base Strategy Class
All trading strategies must inherit from this base class
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Optional, Dict, Any
import pandas as pd
import numpy as np


class SignalType(Enum):
    BUY = 1
    SELL = -1
    HOLD = 0


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[int] = None
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


@dataclass
class MarketData:
    """Standardized market data structure"""
    symbol: str
    timestamp: pd.Timestamp
    open: float
    high: float
    low: float
    close: float
    volume: int
    
    # Optional fields for options/futures
    implied_volatility: Optional[float] = None
    open_interest: Optional[int] = None
    delta: Optional[float] = None
    gamma: Optional[float] = None
    theta: Optional[float] = None
    vega: Optional[float] = None


class Strategy(ABC):
    """Base class for all trading strategies"""
    
    def __init__(self, name: str, config: Dict[str, Any] = None):
        self.name = name
        self.config = config or {}
        self.is_initialized = False
        
    @abstractmethod
    def initialize(self, data: pd.DataFrame) -> None:
        """
        Initialize the strategy with historical data
        Called once before trading starts
        """
        pass
    
    @abstractmethod
    def generate_signal(self, data: pd.DataFrame) -> Optional[Signal]:
        """
        Generate trading signal based on current market data
        Returns Signal or None if no signal
        """
        pass
    
    @abstractmethod
    def calculate_position_size(self, 
                                signal: Signal, 
                                portfolio_value: float,
                                risk_per_trade: float) -> int:
        """
        Calculate position size based on signal and risk parameters
        Returns number of shares/contracts
        """
        pass
    
    def on_data(self, data: pd.DataFrame) -> Optional[Signal]:
        """
        Main entry point called on each new data point
        """
        if not self.is_initialized:
            self.initialize(data)
            self.is_initialized = True
        
        return self.generate_signal(data)
    
    def get_required_data(self) -> Dict[str, Any]:
        """
        Return data requirements for this strategy
        Override to specify required indicators/timeframes
        """
        return {
            "timeframe": "1d",
            "lookback": 100,
            "indicators": []
        }
