#!/bin/bash
# Morning Brief with Discord notification via OpenClaw
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LOG_FILE="/Users/daytrons/.openclaw/workspace/logs/morning_brief.log"

echo "[$(date '+%Y-%m-%d %H:%M')] Generating Morning Brief..." >> "$LOG_FILE"

# Generate brief
BRIEF_JSON=$(python3 "$SCRIPT_DIR/ollama_morning_brief.py" 2>&1)
echo "$BRIEF_JSON" >> "$LOG_FILE"

# Send to Discord
python3 << 'EOF'
import json, subprocess, sys
sys.path.insert(0, '/Users/daytrons/.openclaw/workspace/scripts')

data = json.loads(open('/Users/daytrons/.openclaw/workspace/logs/morning_brief.log').read().split('\n')[-2])

brief = data.get('brief', 'No brief generated')
content = f"📋 **Morning Brief - {data['date']}**\n\n{brief[:1800]}\n\n_Generated by Ollama (zero tokens)_"

# Use openclaw message tool via subprocess
subprocess.run([
    'openclaw', 'message', 'send',
    '--channel', 'discord',
    '--channel-id', '1475212013981532324',
    '--message', content
], capture_output=True)
EOF

echo "[$(date '+%Y-%m-%d %H:%M')] Morning Brief sent to Discord." >> "$LOG_FILE"
