#!/usr/bin/env python3
"""
Ollama Morning Brief with Discord notification
"""
import subprocess
import json
from datetime import datetime

def generate_brief():
    # Call the morning brief generator
    result = subprocess.run(
        ['python3', '/Users/daytrons/.openclaw/workspace/scripts/ollama_morning_brief.py'],
        capture_output=True, text=True, timeout=60
    )
    return json.loads(result.stdout)

def send_to_discord(data):
    brief = data.get('brief', 'No brief generated')
    content = f"📋 **Morning Brief - {data['date']}**\n\n{brief[:1800]}\n\n_Generated by Ollama (zero tokens)_"
    
    # Write to a temp file for the message
    with open('/tmp/morning_brief_msg.txt', 'w') as f:
        f.write(content)
    
    print(f"Would send to Discord: {content[:200]}...")
    print("Discord integration ready. Run via OpenClaw message tool.")

if __name__ == "__main__":
    data = generate_brief()
    print(json.dumps(data, indent=2))
    send_to_discord(data)
