#!/bin/bash
# setup_zero_token_cron.sh - Install zero-token cron system
# Usage: ./setup_zero_token_cron.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

echo "🔧 Zero-Token Cron System Setup"
echo "================================"
echo ""

# Create necessary directories
mkdir -p "$SCRIPT_DIR/logs"

# Make scripts executable
chmod +x "$SCRIPT_DIR/discord_post.sh"
chmod +x "$SCRIPT_DIR/jobs/health_check_job.sh"
chmod +x "$SCRIPT_DIR/jobs/cost_report_job.sh"

echo "✅ Scripts made executable"

# Check if webhook config exists
CONFIG_FILE="$SCRIPT_DIR/.webhook_config"
if [ ! -f "$CONFIG_FILE" ]; then
    echo ""
    echo "⚠️  Webhook configuration needed"
    echo ""
    echo "Please provide your Discord webhook URLs:"
    echo ""
    
    read -p "Admin channel webhook URL: " admin_url
    read -p "Token-tracker channel webhook URL: " token_url
    echo ""
    
    # Create config file
    cat > "$CONFIG_FILE" << EOF
# Discord Webhook Configuration
# Generated by setup_zero_token_cron.sh

ADMIN_WEBHOOK_URL="$admin_url"
TOKEN_TRACKER_WEBHOOK_URL="$token_url"
EOF
    
    chmod 600 "$CONFIG_FILE"
    echo "✅ Webhook config saved to $CONFIG_FILE"
else
    echo "✅ Webhook config already exists"
fi

echo ""
echo "📋 Installation Options:"
echo ""
echo "1. Install launchd plists (recommended - runs automatically)"
echo "2. Skip launchd (manual execution only)"
echo ""
read -p "Choose option (1 or 2): " choice

if [ "$choice" = "1" ]; then
    echo ""
    echo "🚀 Installing launchd plists..."
    
    # Copy plists to LaunchAgents
    cp "$SCRIPT_DIR/launchd/com.dayton.healthcheck.plist" ~/Library/LaunchAgents/
    cp "$SCRIPT_DIR/launchd/com.dayton.costreport.plist" ~/Library/LaunchAgents/
    
    # Load plists
    launchctl load ~/Library/LaunchAgents/com.dayton.healthcheck.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/com.dayton.costreport.plist 2>/dev/null || true
    
    echo "✅ LaunchAgents installed and loaded"
    echo ""
    echo "   Health check: Every 6 hours"
    echo "   Cost report: Every hour at :05"
    echo ""
    echo "📊 View logs:"
    echo "   tail -f $SCRIPT_DIR/logs/healthcheck.log"
    echo "   tail -f $SCRIPT_DIR/logs/costreport.log"
else
    echo ""
    echo "⏭️  Skipped launchd installation"
    echo "   Run jobs manually with:"
    echo "   $SCRIPT_DIR/jobs/health_check_job.sh"
    echo "   $SCRIPT_DIR/jobs/cost_report_job.sh"
fi

echo ""
echo "🧪 Testing..."
echo ""

# Test Discord posting
echo "Sending test message to admin channel..."
TEST_RESULT=$("$SCRIPT_DIR/discord_post.sh" "admin" "🧪 Zero-token cron test message - system installed successfully!")
if [ -n "$TEST_RESULT" ]; then
    echo "✅ Test message sent to admin channel"
else
    echo "⚠️  Test message may have failed (check webhook URL)"
fi

echo ""
echo "================================"
echo "✅ Setup complete!"
echo ""
echo "📁 Location: $SCRIPT_DIR"
echo ""
echo "🛠️  Useful commands:"
echo "   Test health check:  $SCRIPT_DIR/jobs/health_check_job.sh"
echo "   Test cost report:   $SCRIPT_DIR/jobs/cost_report_job.sh"
echo "   View logs:          tail -f $SCRIPT_DIR/logs/*.log"
echo ""
echo "🔄 To manage launchd:"
echo "   Unload:  launchctl unload ~/Library/LaunchAgents/com.dayton.healthcheck.plist"
echo "   Reload:  launchctl load ~/Library/LaunchAgents/com.dayton.healthcheck.plist"
echo ""
